/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static String[] items = {
        "Apple",
        "Banana",
        "Orange",
        "Turnip",
    };

    static int[] prices = {
        2,
        3,
        5,
        6,
    };

    public static void main(String[] args) {
        int n = Math.min(items.length, prices.length);

        System.out.println( "List of items:\nn. item\t\tcost" );
        for (int i = 0; i != n; ++i) {
            System.out.printf("%d. %s\t$%d\n", i + 1, items[i], prices[i]);
        }

        int sum = 0;
        boolean next;
        do {
            next = false;
            Scanner sc = new Scanner(System.in);
            String line = sc.nextLine();
            
            String[] words = line.trim().split("\\s+");
            if (words.length == 2) {
                next = true;
                sum += Integer.parseInt(words[1])
                    * prices[Integer.parseInt(words[0]) - 1];
            }
        } while (next);

        System.out.println(sum);
    }
}
